### ISSUE TITLE
Broken in Craft 3.5.18?

### ISSUE THREAD

**Issue by tomkiss** [mmikkel/Reasons-Craft3#12]
At least it looks that way. Updated and now Reasons is failing, although I can't see any obvious errors appearing, the fields with conditional rules applied just don't appear.

The latest release of Craft includes many accessibility improvements which could be related.

**Comment by mmikkel** [comment]
Thanks for reporting that @tomkiss. 

Yep, absolutely everything seems broken on 3.5.18; P&T likely changed the CP markup in some crucial spots for those a11y improvements. I'll have to dig in, hopefully it's an easy fix.

**Comment by mmikkel** [comment]
@tomkiss Actually, did some debugging and it seems like only Lightswitch fields are affected. Which types of toggle fields (i.e. the fields showing/hiding other fields) are you seeing issues with? Lightswitches, or any other field types?

**Comment by mmikkel** [comment]
Tested every fieldtype and AFAIK only Lightswitch fields were bugged. Just put out [Reasons 2.2.4](https://github.com/mmikkel/Reasons-Craft3/releases/tag/2.2.4), which should resolve the issue.

Thanks again for reporting!

**Comment by tomkiss** [comment]
Amazing, quick fix! Thanks.

(I was only using Reasons for light switch fields incidentally)
