### ISSUE TITLE
Duplicate query issue with large data

### ISSUE THREAD

**Issue by parthi-me** [mmikkel/Reasons-Craft3#15]
Hi,

We have a craft cms site, with nearly 300 sections, each section has only one entry type with 5 or 6 conditional fields. We see a huge delay when switching over control panel menu pages. This occurs on all menus even when switching between settings, utilities etc,

Our initial findings are showing there are a lot of duplicate queries initiated by reasons plugin is the cause for this delay. 
For example, when we load the utilities page, after disabling the plugin only 60 odd queries were running, After enabling we see nearly 12000 queries were running. See attached,
![craft-with-reasons](https://user-images.githubusercontent.com/10112283/148916524-bc24ada4-cd60-455e-8d77-ced2dd282cd5.jpg)
![Craft-without-reasons](https://user-images.githubusercontent.com/10112283/148916533-fb4332ae-5fa6-47dd-895b-ba3374a361c1.jpg)

Could we load the queries only on the pages needed?

System info:
PHP version	7.4.24
OS version	Linux 5.4.0-91-generic
Database driver & version	MySQL 5.7.35
Image driver & version	GD 7.4.24
Craft edition & version	Craft Pro 3.7.28
Yii version	2.0.44
Twig version	v2.14.10
Guzzle version	7.4.1

Reason plugin version - 2.2.5

**Comment by mmikkel** [comment]
> nearly 300 sections

Whoa 🤯  

@parthi-me Reasons caches all data in production (i.e. when `devMode` is `false`), so I assume you're primarily running into this issue in development?

**Comment by parthi-me** [comment]
Yes @mmikkel Above mentioned site is in development mode.

**Comment by mmikkel** [comment]
@parthi-me I've implemented a fix – if you'd be able to help me test it, that'd be great:

Change your `mmikkel/reasons` dependency in `composer.json` to `dev-master#bab707bab9a58bb1b385939a9ae1c95f7986a13e as 2.2.5`. Then run `composer update mmikkel/reasons`.

Thanks!

**Comment by parthi-me** [comment]
Thank you @mmikkel, Above fix is working fine in the initial testing. Attached is the same utilities page, which is loading only 67queries, reduced from 12000 queries previously.
![Screenshot 2022-01-11 203736](https://user-images.githubusercontent.com/10112283/148968633-f318c85a-e5b9-46c0-bb0e-a9b75af79508.jpg)

**Comment by mmikkel** [comment]
@parthi-me Thank you for the follow-up! That’s quite an improvement…

I’ll get a release out with that fix ASAP.

**Comment by mmikkel** [comment]
@parthi-me Just tagged release [2.2.6](https://github.com/mmikkel/Reasons-Craft3/releases/tag/2.2.6) with that fix. Thanks for reporting!
