### ISSUE TITLE
Reasons doesn't work in entry select field "Add new entry" modals

### ISSUE THREAD

**Issue by alisonweirsmith** [mmikkel/Reasons-Craft3#16]
I've got an entry type with a lightbox to toggle between to fields - a Matrix field and a Super Table field. The toggle applies to the entire field and works perfectly in the normal "Add new entry" from the "All Entries" dashboard view.

What doesn't work is the toggle when you opt to add a new entry from the "Select an Entry" entry field. Please see diagram below for explanation

![Test-ezyVet](https://user-images.githubusercontent.com/31128856/168959275-b4e467aa-ff30-46bf-919a-9e4889a5d02c.png)
.

**Comment by mmikkel** [comment]
Thanks for reporting that! Just tagged Reasons 2.3.0 which should resolve this issue.
