### ISSUE TITLE
Update from Craft 3 + Reasons to Craft 4: how to get fields' conditions from template?

### ISSUE THREAD

**Issue by romainpoirier** [mmikkel/Reasons-Craft3#18]
I've just updated from Craft 3 to Craft 4. I was previously using the [Reasons plugin][1] for CP but also front-end purpose. On front-end, I was printing field layouts and show/hide the fields based on the same Reasons conditions found in the CP.

Unfortunately, this plugin has been stopped for Craft 4 in profit of the native conditional fields. However, I don't find out the equivalent of what I could achieve using Reasons.

This is what I was doing in Craft 3 + Reasons:

    {% set conditionals = [] %}
    % for key, value in craft.app.getPlugins().getPlugin('reasons').reasons.getData().conditionals  %}
    	{%
    		if 'section' in key
    		and (key | split(':') | last) | number_format == craft.app.sections.getSectionByHandle('companies').id ?? -1
    	%}
    		{% set conditionals = value %}
    	{% endif %}
    {% endfor %}
    
    {% set rules = [] %}
    {% set syncedFields = [] %}
    {% set syncedHandles = [] %}
    {% set hiddenFields = [] %}
    {% for id, condition in conditionals %}
    	{% set syncedFields = syncedFields | merge([condition.0.0.0.fieldId ?? null]) | filter | unique %}
    	{% set handle = craft.app.fields.getFieldById(condition.0.0.0.fieldId ?? null).handle ?? null %}
    	{% set syncedHandles = syncedHandles | merge(["{handle}: '{value}'" | t({
    		handle: handle,
    		value: company[handle].value ?? company[handle] ?? null
    	})]) | filter | unique %}
    	{% set hiddenFields = hiddenFields | merge([id ?? null]) | filter %}
    	{% set condition = {
    		sync: condition.0.0.0.fieldId ?? null,
    		field: id ?? null,
    		rule: '{compare} {value}' | t({
    			compare: condition.0.0.0.compare,
    			value: condition.0.0.0.value
    		})
    	} %}
    {% endfor %}

In my case, the intended context here is quite simple: it's checking a Lightswitch field from another field. If the main field is switched on, subfields will be shown.

What would be the equivalent in Craft 4?

  [1]: https://github.com/mmikkel/Reasons-Craft3

**Comment by mmikkel** [comment]
I don't understand the intention with that code, but I assume there's a good reason why can't you just use a simple conditional in your front end template? I.e. something like

```
{% if entry.mainLightswitchField %}
    {# Display sub fields #}
{% endif %}
```

In any case – I haven't done a lot of digging into how the core conditionals in Craft 4 works, but for elements (like entries) they're attached to the elements' field layouts, so that's probably where you need to start.

If the use case is simply to get an array of all hidden fields' handles for a particular entry, that's relatively straight-forward:

```twig
{# Get visible (i.e. not hidden) fields for this entry #}
{% set visibleFields = entry.fieldLayout.getVisibleCustomFields(entry) %}

{# There's no method for getting hidden fields, but we can get them by pulling all fields and then filter out the visible ones #}
{% set hiddenFields = entry.fieldLayout.getCustomFields()|without(visibleFields) %}

{# The column filter is an easy way to get all the field handles #}
{% set hiddenFieldHandles = hiddenFields|column('handle') %}
```

**Comment by romainpoirier** [comment]
Thank you for your reply.

> I don't understand the intention with that code

The idea is to use the CP field layout settings, that include conditionals, to get the same result on the front-end. So some fields are hidden on the front-end depending on another field value (in my case, a Lightswitch and/or a Radio field). This is used to have a totally dynamic template, ie. a copy of the CP field layout. So not every Lightswitch and/or a Radio field should be conditional, only those setup with conditions. And I've to check the rules attached to these conditions, so I can't base the test only on the visible status.

After pre-processing that, I'm showing/hiding the fields using AlpineJS:
```
'x-data': (syncedHandles is not empty) ? "{ {syncedHandles} }" | t({
	syncedHandles: syncedHandles | join(',')
})
```
Then, on fields, I'm using the `x-show` attribute.

Concrete example:

- On form: `x-data="{ companyLiableForVat: 'yes' }"`
- On field that should be visible/hidden depending on `companyLiableForVat` field value: `x-show="companyLiableForVat == 'yes'"`

About your example:
```
{% set hiddenFields = entry.fieldLayout.getCustomFields()|without(visibleFields) %}
{% set hiddenFieldHandles = hiddenFields|column('handle') %}
```

This is working fine, thank you. However, this doesn't get the conditional rules, which I still need to add my JS hide/show custom behavior on fields. Do you have any idea how to achieve this?
