### ISSUE TITLE
Enhancement Request - Can you make this work with NEO?

### ISSUE THREAD

**Issue by vaughn-taylor** [mmikkel/Reasons-Craft3#7]
It's great that this plugin's features can be accessed directly from the field settings cog, but it's only available if the field is being used natively. It does not work when inside NEO.

**Comment by mmikkel** [comment]
Not happening, sorry :)

**Comment by vaughn-taylor** [comment]
That's fine. Just thought I'd ask.

**Comment by mmikkel** [comment]
No worries @vaughn-taylor – hopefully conditionals are coming to core soon (3.6 or 3.7, maybe) and that they work "everywhere" (the fact that the feature _is_ coming to core is why Reasons is in feature-freeze mode) :)

**Comment by vaughn-taylor** [comment]
I cannot wait to have conditionals as native functionality and I wasn't aware that we may be seeing them soon, so thanks for the heads up. Brandon told me awhile back that we would see "NEO-like" functionality in 4.x, so it's going to be a beautiful world when we have both.
