### ISSUE TITLE
Conditional fields don't show after updating to 3.5.3?

### ISSUE THREAD

**Issue by tommysvr** [mmikkel/Reasons-Craft3#8]
I updated to 3.5.3 today and it looks to have broken Reasons. I'm able to access the Conditional options when editing the Entry Type, but the conditional field doesn't show at all after adding criteria. In the second screenshot, the field should show to the right of 'Child Layout'.

![Screen Shot 2020-08-13 at 2 53 00 pm](https://user-images.githubusercontent.com/867566/90095716-d522e480-dd74-11ea-9cf8-8452fbbee5d7.png)
![Screen Shot 2020-08-13 at 2 53 29 pm](https://user-images.githubusercontent.com/867566/90095723-d81dd500-dd74-11ea-880b-d5343b142893.png)

**Comment by mmikkel** [comment]
Hi @tommysvr – thanks for reporting, I'm able to reproduce. Will get a fix out as soon as possible.

**Comment by mmikkel** [comment]
Should be resolved in [Reasons 2.2.1](https://github.com/mmikkel/Reasons-Craft3/releases/tag/2.2.1)
